#!/bin/bash

sbatch batch-files/barnesHut-ser-batch
sbatch batch-files/barnesHut-par8-batch
sbatch batch-files/barnesHut-par16-batch
sbatch batch-files/barnesHut-par32-batch
sbatch batch-files/barnesHut-par64-batch
sbatch batch-files/barnesHut-par68-batch
sbatch batch-files/barnesHut-par68-varsteps-batch

