#!/bin/bash
#----------------------------------------------------
# Sample Slurm job script
#   for TACC Stampede2 KNL nodes
#
#   *** OpenMP Job on Normal Queue ***
# 
# Last revised: 20 Oct 2017
#
# Notes:
#
#   -- Launch this script by executing
#   -- Copy/edit this script as desired.  Launch by executing
#      "sbatch knl.openmp.slurm" on a Stampede2 login node.
#
#   -- OpenMP codes run on a single node (upper case N = 1).
#        OpenMP ignores the value of lower case n,
#        but slurm needs a plausible value to schedule the job.
#
#   -- Default value of OMP_NUM_THREADS is 1; be sure to change it!
#
#   -- Increase thread count gradually while looking for optimal setting.
#        If there is sufficient memory available, the optimal setting
#        is often 68 (1 thread per core) or 136 (2 threads per core).
#----------------------------------------------------
#SBATCH -J brute          # Job name
#SBATCH -o batch-out/brute.o%j         # Name of stdout output file
#SBATCH -e batch-out/brute.e%j         # Name of stderr error file
#SBATCH -p normal          # Queue (partition) name
#SBATCH -N 1               # Total # of nodes (must be 1 for OpenMP)
#SBATCH -n 1               # Total # of mpi tasks (should be 1 for OpenMP)
#SBATCH -t 16:00:00        # Run time (hh:mm:ss)
#SBATCH --mail-user=campbeda@utexas.edu
#SBATCH --mail-type=all    # Send email at begin and end of job
#SBATCH -A EE-382C-EE-361C-Mult
# Other commands must follow all #SBATCH directives...
module list
pwd
date
# Set thread count (default value is 1)...
export OMP_NUM_THREADS=1
# Launch OpenMP code...
#echo "Running number of threads N1"
./bruteForce 500 $WORK/input/in2_10.txt $WORK/output/bruteForceN1_2_10.txt 


./bruteForce 500 $WORK/input/in2_11.txt $WORK/output/bruteForceN1_2_11.txt 
./bruteForce 500 $WORK/input/in2_12.txt $WORK/output/bruteForceN1_2_12.txt 
./bruteForce 500 $WORK/input/in2_13.txt $WORK/output/bruteForceN1_2_13.txt 
./bruteForce 500 $WORK/input/in2_14.txt $WORK/output/bruteForceN1_2_14.txt 
./bruteForce 500 $WORK/input/in2_15.txt $WORK/output/bruteForceN1_2_15.txt 
#./barnesHut 500 $WORK/input/in2_17.txt $WORK/output/barnesHutN1_2_17.txt 
#./bruteForce 500 $WORK/input/in2_20.txt $WORK/output/bruteForceN1_2_20.txt  

# export OMP_NUM_THREADS=8
# # Launch OpenMP code...
# echo "Running number of threads N8"
# ./barnesHutParallel 500 $WORK/input/in2_10.txt $WORK/output/barnesHutParallelN8_2_10.txt 
# ./barnesHutParallel 500 $WORK/input/in2_11.txt $WORK/output/barnesHutParallelN8_2_11.txt 
# ./barnesHutParallel 500 $WORK/input/in2_12.txt $WORK/output/barnesHutParallelN8_2_12.txt 
# ./barnesHutParallel 500 $WORK/input/in2_13.txt $WORK/output/barnesHutParallelN8_2_13.txt 
# ./barnesHutParallel 500 $WORK/input/in2_14.txt $WORK/output/barnesHutParallelN8_2_14.txt 
# ./barnesHutParallel 500 $WORK/input/in2_15.txt $WORK/output/barnesHutParallelN8_2_15.txt 
#./barnesHutParallel 500 $WORK/input/in2_17.txt $WORK/output/barnesHutParallelN8_2_17.txt #maybe if we have time
#./barnesHutParallel 500 $WORK/input/in2_20.txt $WORK/output/barnesHutParallelN8_2_20.txt #maybe if we have time

# export OMP_NUM_THREADS=16
# # Launch OpenMP code...
# echo "Running number of threads N16"
# ./barnesHutParallel 500 $WORK/input/in2_10.txt $WORK/output/barnesHutParallelN16_2_10.txt 
# ./barnesHutParallel 500 $WORK/input/in2_11.txt $WORK/output/barnesHutParallelN16_2_11.txt 
# ./barnesHutParallel 500 $WORK/input/in2_12.txt $WORK/output/barnesHutParallelN16_2_12.txt 
# ./barnesHutParallel 500 $WORK/input/in2_13.txt $WORK/output/barnesHutParallelN16_2_13.txt 
# ./barnesHutParallel 500 $WORK/input/in2_14.txt $WORK/output/barnesHutParallelN16_2_14.txt 
# ./barnesHutParallel 500 $WORK/input/in2_15.txt $WORK/output/barnesHutParallelN16_2_15.txt 
# ./barnesHutParallel 500 $WORK/input/in2_17.txt $WORK/output/barnesHutParallelN16_2_17.txt 
# ./barnesHutParallel 500 $WORK/input/in2_20.txt $WORK/output/barnesHutParallelN16_2_20.txt  

# export OMP_NUM_THREADS=32
# # Launch OpenMP code...
# echo "Running number of threads N32"
# ./barnesHutParallel 500 $WORK/input/in2_10.txt $WORK/output/barnesHutParallelN32_2_10.txt 
# ./barnesHutParallel 500 $WORK/input/in2_20.txt $WORK/output/barnesHutParallelN32_2_20.txt  
# ./barnesHutParallel 500 $WORK/input/in2_15.txt $WORK/output/barnesHutParallelN32_2_15.txt 
# ./barnesHutParallel 500 $WORK/input/in2_11.txt $WORK/output/barnesHutParallelN32_2_11.txt 
# ./barnesHutParallel 500 $WORK/input/in2_12.txt $WORK/output/barnesHutParallelN32_2_12.txt 
# ./barnesHutParallel 500 $WORK/input/in2_13.txt $WORK/output/barnesHutParallelN32_2_13.txt 
# ./barnesHutParallel 500 $WORK/input/in2_14.txt $WORK/output/barnesHutParallelN32_2_14.txt 
# ./barnesHutParallel 500 $WORK/input/in2_17.txt $WORK/output/barnesHutParallelN32_2_17.txt 

# export OMP_NUM_THREADS=64
# # Launch OpenMP code...
# echo "Running number of threads N64"
# ./barnesHutParallel 500 $WORK/input/in2_10.txt $WORK/output/barnesHutParallelN64_2_10.txt 
# ./barnesHutParallel 500 $WORK/input/in2_20.txt $WORK/output/barnesHutParallelN64_2_20.txt  
# ./barnesHutParallel 500 $WORK/input/in2_15.txt $WORK/output/barnesHutParallelN64_2_15.txt 
# ./barnesHutParallel 500 $WORK/input/in2_11.txt $WORK/output/barnesHutParallelN64_2_11.txt 
# ./barnesHutParallel 500 $WORK/input/in2_12.txt $WORK/output/barnesHutParallelN64_2_12.txt 
# ./barnesHutParallel 500 $WORK/input/in2_13.txt $WORK/output/barnesHutParallelN64_2_13.txt 
# ./barnesHutParallel 500 $WORK/input/in2_14.txt $WORK/output/barnesHutParallelN64_2_14.txt 
# ./barnesHutParallel 500 $WORK/input/in2_17.txt $WORK/output/barnesHutParallelN64_2_17.txt 


# export OMP_NUM_THREADS=68
# # Launch OpenMP code...
# echo "Running number of threads N68"
# ./barnesHutParallel 500 $WORK/input/in2_10.txt $WORK/output/barnesHutParallelN68_2_10.txt 
# ./barnesHutParallel 500 $WORK/input/in2_20.txt $WORK/output/barnesHutParallelN68_2_20.txt  
# ./barnesHutParallel 500 $WORK/input/in2_15.txt $WORK/output/barnesHutParallelN68_2_15.txt 
# ./barnesHutParallel 500 $WORK/input/in2_11.txt $WORK/output/barnesHutParallelN68_2_11.txt 
# ./barnesHutParallel 500 $WORK/input/in2_12.txt $WORK/output/barnesHutParallelN68_2_12.txt 
# ./barnesHutParallel 500 $WORK/input/in2_13.txt $WORK/output/barnesHutParallelN68_2_13.txt 
# ./barnesHutParallel 500 $WORK/input/in2_14.txt $WORK/output/barnesHutParallelN68_2_14.txt 
# ./barnesHutParallel 500 $WORK/input/in2_17.txt $WORK/output/barnesHutParallelN68_2_17.txt 

# echo "Running Varied Timetemps"
# ./barnesHutParallel 100 $WORK/input/in2_20.txt $WORK/output/barnesHutParallelN68_2_20_steps100.txt  
# ./barnesHutParallel 200 $WORK/input/in2_20.txt $WORK/output/barnesHutParallelN68_2_20_steps200.txt  
# ./barnesHutParallel 300 $WORK/input/in2_20.txt $WORK/output/barnesHutParallelN68_2_20_steps300.txt  
# ./barnesHutParallel 400 $WORK/input/in2_20.txt $WORK/output/barnesHutParallelN68_2_20_steps400.txt  
# ./barnesHutParallel 500 $WORK/input/in2_20.txt $WORK/output/barnesHutParallelN68_2_20_steps500.txt  
# ./barnesHutParallel 600 $WORK/input/in2_20.txt $WORK/output/barnesHutParallelN68_2_20_steps600.txt  
# ./barnesHutParallel 700 $WORK/input/in2_20.txt $WORK/output/barnesHutParallelN68_2_20_steps700.txt  
# ./barnesHutParallel 800 $WORK/input/in2_20.txt $WORK/output/barnesHutParallelN68_2_20_steps800.txt  
# ./barnesHutParallel 900 $WORK/input/in2_20.txt $WORK/output/barnesHutParallelN68_2_20_steps900.txt  


# ---------------------------------------------------
